config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  root to: "users#show"
  resources :orders do
    resources :comments, only: :create
  end
  resources :order_items, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :order
  belongs_to :user
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :sending_user, class_name: 'User', foreign_key: 'sending_user_id'
  has_many :order_items
  accepts_nested_attributes_for :order_items, allow_destroy: true
  has_many :comments
  
  validates :delivery_day, presence: true
  validate :delivery_day_must_be_future
  validates :sending_user, presence: true
  
  private

  def delivery_day_must_be_future
    errors.add(:delivery_day, 'must be a future date') if delivery_day.present? && delivery_day < Date.tomorrow
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  
  validates :item_name, presence: true
  validates :amount, presence: true, numericality: { only_integer: true }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :company_name,    presence: true
  validates :last_name,       presence: true, format: { with: /\A[ぁ-んァ-ヶ一-龥々ー]+\z/ }
  validates :first_name,      presence: true, format: { with: /\A[ぁ-んァ-ヶ一-龥々ー]+\z/ }
  validates :kana_last_name,  presence: true, format: { with: /\A[ァ-ヶー－]+\z/ }
  validates :kana_first_name, presence: true, format: { with: /\A[ァ-ヶー－]+\z/ }
  validates :phone_number,    presence: true, length: { minimum: 10, maximum: 11 }, numericality: { only_integer: true }
  validates :password, format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i }
  
  has_many :orders
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  private
  
  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
    end
  end
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,
                                      keys: [:company_name, :last_name, :first_name, :kana_last_name, :kana_first_name, :phone_number])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @order = Order.find(params[:order_id])
    @comment = @order.comments.build(comment_params)
    if @comment.save
      redirect_to order_path(@order)
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:content).merge(user_id: current_user.id)
  end
end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController
  
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  
  def index
    @orders = Order.all
    @matched_orders = @orders.select { |order| order.sending_user_id == current_user.id || order.user_id == current_user.id }
  end
  
  def new
    @order = Order.new
    @order.order_items.build
  end

  def create
    @order = Order.new(order_params)
    @order.user_id = current_user.id
    if @order.save
      redirect_to root_path
    else
      render :new
    end
  end
  
  def edit
    @order = Order.find(params[:id])
    if @order.user_id == current_user.id
      render :edit
    else
      redirect_to root_path
    end
  end
  
  def update
    @order = Order.find(params[:id])
    if @order.update(order_params)
      redirect_to order_path(@order)
    else
      render :edit
    end
  end
  
  
  def destroy
    @order = Order.find(params[:id])
    if current_user == @order.user
      @order.order_items.destroy_all
      @order.destroy
      redirect_to root_path
    else
      redirect_to order_path
    end
  end
  
  def show
    @order = Order.includes(:order_items).find(params[:id])
    @comment = Comment.new
    @comments = @order.comments.includes(:user)
  end
    
  private
  def order_params
    params.require(:order).permit(:delivery_day, :sending_user_id, 
      order_items_attributes:[:id, :item_name, :amount, :memo, :_destroy])
      .merge(user_id: current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: :show
  
  def show
    @user = current_user
    @orders = Order.where(user_id: current_user.id)
    @matched_orders = Order.where(sending_user_id: current_user.id)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OrderLink</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>
</head>

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/orders/_order_item_fields.html.erb
<style>
  .new-items {
    display: flex;
    flex-wrap: wrap;
    justify-content: space-between;
  }

  .new-items .field {
    flex-basis: calc(33.33% - 30px); /* 調整された値 */
    margin-right: 30px; /* 調整された値 */
    margin-bottom: 15px;
    display: flex;
    align-items: center;
  }

  .new-items .field:last-child {
    margin-right: 0;
  }

  .field .remove-field {
    margin-left: 10px;
    display: flex;
    align-items: center;
  }

  .field .weight-bold-text,
  .field .remove-field {
    writing-mode: horizontal-tb;
    text-orientation: upright;
  }
  .delete-button {
    text-decoration: none;
    color: black;
    background-color: lightgray;
    font-size: 20px;
    padding: 3px;
    margin-left: 8px;
  }
</style>

<div class="nested-fields">
  <div class="new-items">
    <div class="field">
      <%= f.text_field :item_name, class: "items-text", id: "item-name" %>
    </div>

    <div class="field">
      <%= f.text_field :amount, class: "items-text", id: "item-info" %>
      <div class="weight-bold-text">
        g
      </div>
    </div>

    <div class="field">
      <%= f.text_field :memo, class: "memo", id: "item-info" %>
      <div class="remove-field">
        <%= link_to_remove_association '削除', f, class: "delete-button" %>
      </div>
    </div>
  </div>
</div>

app/views/orders/edit.html.erb
<style>
  .items-sell-title {
    margin: 50px;
  }
  .items-sell-main {
    display: flex;
    flex-direction: column;
    align-items: center;
  }
  .new-items .field:last-child {
    margin-right: 0;
  }
  
  .logo_image {
    position: absolute;
    top: 20px;
    left: 30px;
  }
  .fields {
    margin-bottom: 20px;
  }
  .new-items {
    display: flex;
    flex-direction: column;
    align-items: flex-start;
  }

  .field .remove-field {
    margin-left: 10px;
    display: flex;
    align-items: center;
  }

  .weight-bold-text{
    padding-bottom: 10px;
  }
  .items-text-main {
    margin-right: 42px;
  }
  .add-link {
    text-decoration: none;
    color: black;
    padding: 10px;
    background-color: lightgray;
  }
  .order-text {
    margin-top: 30px;
    margin-bottom: 30px;
    font-size: 20px;
  }
  .back-btn {
    background: lightgray;
    color: black;
    text-decoration: none;
    display: block;
    margin: 30px 0 0 40px;
    width: 70%;
    height: 50px; 
    text-align: center;
    padding: 12px;
  }
  .submit-btn {
    background: #bad4d1;
    border: none;
    color: black;
    width: 70%;
    height: 50px;
    margin-left: 40px;
  }
  
  .order-already {
    display: flex;
    align-items: center;
  }
  
</style>

<div class="items-sell-contents">
  <div class="items-sell-main">
    <%= link_to image_tag('DF2C122C-D754-4D23-916F-539CB5B324BF.jpg', size: '185x50'), root_path, class: "logo_image" %>
    <h2 class="items-sell-title" style="margin-top: 50px;">発注変更</h2>

    <%= form_with model: @order, local: true do |f| %>
      <%= render 'shared/error_messages', model: @order %>

      <div class="new-items">
        <% @order.order_items.each do |item| %>
          <div class="order-already">
            <div class="fields">
              <%= f.fields_for :order_items, item do |item_form| %>
                <%= render 'order_item_fields', f: item_form %>
              <% end %>
            </div>
          </div>
        <% end %>
        
        <div class="links">
          <%= link_to_add_association '追加', f, :order_items, partial: 'order_item_fields', class: "add-link" %>
        </div>
      </div>
      
      <div class="order-text">
        納品日
        <%= f.date_field :delivery_day, class: "calender" %>
      </div>
    
      <div class="submit_button">
        <%= f.submit "変更する", class: "submit-btn" %>
        
        <%= link_to 'もどる', order_path(@order), class: "back-btn" %>
      </div>
    <% end %>
  </div>
</div>

app/views/orders/new.html.erb
<style>
  .items-sell-title {
    margin: 50px;
  }
  .items-sell-main {
    display: flex;
    flex-direction: column;
    align-items: center;
  }
  .new-items .field:last-child {
    margin-right: 0;
  }
  
  .logo_image {
    position: absolute;
    top: 30px;
    left: 35px;
  }
  .fields {
    display: flex;
    margin-bottom: 20px; /* 追加 */
  }
  .new-items {
    display: flex;
    flex-wrap: wrap;
    justify-content: space-between;
  }

  .field .remove-field {
    margin-left: 10px;
    display: flex;
    align-items: center;
  }
  .sending_user {
    margin-bottom: 70px;
    font-size: 20px;
    padding-right: 15px;
  }
  .weight-bold-text{
    font-size: 20px;
  }

  .items-text-main {
    margin-right: 42px;
  }
  .add-link {
    text-decoration: none;
    color: black;
    padding: 10px;
    background-color: lightgray;
    margin-left: 700px;
    font-size: 20px;
  }
  .order-text {
    margin-top: 30px;
    margin-bottom: 60px;
    font-size: 20px;
  }
  .back-btn {
    background: lightgray;
    color: black;
    padding: 16px 211px;
    text-decoration: none;
    margin-left: 160px;
    font-size: 20px;
  }
  .submit-btn {
    background: #bad4d1;
    border: none;
    color: black;
    width: 60%;
    height: 50px;
    margin-bottom: 4vh;
    display: flex;
    justify-content: center;
    align-items: center; /* 追加 */
    margin-left: auto; /* 追加 */
    margin-right: auto; /* 追加 */
    font-size: 20px;
  }
  .amount {
    margin-left: 230px;
  }
  
  .field {
    font-size: 20px;
  }
  
</style>

<div class="items-sell-contents">
  <div class="items-sell-main">
    <%= link_to image_tag('DF2C122C-D754-4D23-916F-539CB5B324BF.jpg', size: '220x70'), root_path, class:"logo_image" %>
    <h2 class="items-sell-title" style="margin-top: 50px;">発注登録</h2>

    <%= form_with(model: @order, url: orders_path, local: true) do |f| %>
    
    <%= render 'shared/error_messages', model: @order %>

      <div class="field">
        <%= f.label :sending_user_id, class: "sending_user" do %>
          送信先
        <% end %>
        <%= f.collection_select :sending_user_id, User.where.not(id: current_user.id), :id, :company_name, { include_blank: true }, class: "select-field" %>
      </div>
      
      <div class="fields">
        <div class="field">
          <div class="item-name">
            品名
          </div>
        </div>

        <div class="field">
          <div class="amount">
            数量
          </div>
        </div>

        <div class="field">
          <div class="memo">
            　　　　　　　　　　　  備考欄(任意)
          </div>
        </div>
      </div>

      <div class="new-items">
        <%= f.fields_for :order_items do |item_form| %>
          <%= render 'order_item_fields', f: item_form %>
        <% end %>
      </div>
      
      <div class="links">
        <%= link_to_add_association '追加', f, :order_items, partial: 'order_item_fields', class: "add-link" %>
      </div>
      
      <div class="order-text">
        納品日
        <%= f.date_field :delivery_day, class:"calender" %>
      </div>
    
      <div class="submit_button">
        <%= f.submit "送信する", class:"submit-btn" %>
        <%= link_to 'もどる', root_path, class:"back-btn" %>
      </div>
    <% end %>
  </div>
</div>

app/views/orders/show.html.erb
<style>
  .order-edit {
    text-decoration: none;
  }
  .order-destroy {
    text-decoration: none;
  }
  .contents {
    display: flex;
    flex-direction: column;
    align-items: center;
    margin: 10px 0;
  }
  .order-item-index {
    display: flex;
    justify-content: center;
    margin: 10px 0;
    font-size: 30px;
  }
  .title-index {
    display: flex;
    flex-direction: column;
    align-items: center;
    margin-bottom: 30px;
  }
  h2 {
    font-weight: bold;
  }
  .edit-delete {
    display: flex;
    align-items: center;
    justify-content: center;
    margin: 20px;
  }
  .order_item_name {
    text-align: left;
    margin-right: 50px;
    width: 200px;
    margin-left: 400px;
    white-space: nowrap; 
    text-overflow: ellipsis; 
  }
  .order_item_amount {
    text-align: left;
    margin-right: 40px;
    width: 100px;
  }
  .order_item_memo {
    text-align: left; 
    width: 400px;
  }
  .index-delivery {
    margin-bottom: 60px;
    font-size: 30px;
    text-align: center;
    position: relative;
  }

  .delivery-line {
    position: absolute;
    left: 0;
    right: 0;
    bottom: 0;
    height: 1px;
    background-color: #ccc;
  }

  .order-edit {
    text-align: center;
    background-color: #bad4d1;
    font-size: 30px;
    color: black;
    margin: 10px 0px;
    padding: 1vh 5vw;
  }
  .order-destroy {
    text-align: center;
    background-color: lightgray;
    font-size: 30px;
    color: black;
    margin: 20px 20px;
    padding: 1vh 5vw;
  }
  .logo-image {
    width: 260px;
    height: 80px;
    margin: 30px;
  }
  .container {
    display: flex;
    flex-direction: column;
    align-items: center;
    margin-bottom: 50px; 
    background-color: #e6f0f0
  }
  .comments {
    margin: 50px;
    flex-direction: column; 
    align-items: flex-start;
  }
  .comment-form {
    width: 500px;
    height: 60px;
    margin: 40px;
    display: flex;
    align-items: center;
    justify-content: space-between; 
  }
  .comment-input {
    flex: 1;
    margin-right: 10px;
  }
  .submit-btn {
    width: 70px;
    height: 50px;
    background-color: #bad4d1;
    border: none;
    margin-top: 45px;
  }
  .comment-index {
    margin: 30px 0 ;
    font-size: 25px;
  }
  .create-time {
    margin-left: 5px;
  }
  .comment-forms {
    display: flex;
  }
</style>

<%= link_to image_tag("DF2C122C-D754-4D23-916F-539CB5B324BF.jpg", class:"logo-image"), root_path %>
<div class="title-index">
  <h2>発注内容</h2>
</div>
<div class="contents">
  <div class="index-delivery">
    <span>納品日：</span>
    <%= @order.delivery_day %>
    <div class="delivery-line"></div>
  </div>
  
  <% @order.order_items.each do |order_item| %>
    <div class="order-item-index">
      <p class="order_item_name">◇<%= order_item.item_name %></p>
      <p class="order_item_amount"><%= order_item.amount %>g</p>
      <p class="order_item_memo"><%= order_item.memo %></p>
    </div>
  <% end %>
</div>

<% if user_signed_in? && @order.user == current_user %>
<div class="edit-delete">
  <%= link_to '編 集', edit_order_path(@order.id), class: "order-edit" %>
  <%= link_to '削 除', order_path(@order.id), method: :delete, class: "order-destroy" %>
</div>
<% end %>

<div class="container">
  <%= form_with(model: [@order, @comment] , url: order_comments_path(@order), local: true) do |form| %>
    <div class="comments">
      <div class= "comment-index">コメント一覧</div>
      <% @comments.each do |comment| %>
        <p>
          <strong><%= comment.user.company_name %>：</strong>
          <%= comment.content %>
          <%= comment.created_at.strftime("%Y-%m-%d %H:%M") %>
        </p>
      <% end %>
    </div>
    <div class= "comment-forms">
    <%= form.text_area :content, placeholder: "コメントする", rows: "2", class: "comment-form" %>
    <%= form.submit "送信", class: "submit-btn" %>
    </div>
  <% end %>
</div>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_header.html.erb
<header class='top-page-header'>
  <div class='nav'>
    <ul class='lists-right'>
    <% if user_signed_in? %>
      <li><%= link_to current_user.company_name, "#", class: "user-company_name" %></li>
      <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %></li>
    <% else %>
      <li><%= link_to 'ログイン', new_user_session_path, class: "login" %></li>
      <li><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></li>
    <% end %>
    </ul>
  </div>
</header>

app/views/users/show.html.erb
    <style>
      
      .furima-icon {
        width: 260px;
        height: 80px;
        margin-left: 5px;
      }
      .infomation {
        font-size: 20px;
        margin: 30px 0 50px 100px;
      }
      .nav-item {
        padding: 10px;
        font-size: 20px;
      }
      .contents-row {
        margin: 50px 0 50px 100px;
        font-size: 20px;
        padding: 10px;
        border: solid 4px #bad4d1;
        width: 85vw;
      }
      .show-page {
        text-decoration: none;
        color: black;
        font-size: 20px;
      }
      .create-order {
        text-decoration: none;
        padding: 15px;
        background-color: #bad4d1;
        color: black;
        margin-left: 650px;
      }
      .logout-button {
        text-decoration: none;
        padding: 15px;
        background-color: lightgray;
        color: black;
      }
      .container {
    display: flex;
    align-items: center;
    margin-right: 20px;
  }
  
  .nav {
    display: flex;
    align-items: center;
    margin-right: 10px;
  }
  
  .nav-item {
    margin-left: 10px;
  }
      
    </style>

  <div class="container">
    <header class="d-flex flex-wrap py-3 mb-4 border-bottom">
      <%= link_to image_tag("DF2C122C-D754-4D23-916F-539CB5B324BF.jpg", class:"furima-icon"), root_path %>
  <ul class="nav nav-pills justify-content-center">
    <li class="nav-item">
      <%= link_to "発注作成", new_order_path, class: "create-order", "aria-current": "page"  %>
    </li>
    <li class="nav-item">
      <%= link_to "ログアウト", destroy_user_session_path, class: "logout-button",  "aria-current": "page" %>
    </li>
  </ul>
    </header>
  </div>

<div class="infomation">
<p>こんにちは、<%= current_user.company_name %> 様</p>
</div>

<div class="contents-row">
  <p>送信一覧</p>
  <% @orders.reverse_each do |order| %>
    <div class="order-index">
      ◇ <%= link_to order.delivery_day, order_path(order), class: "show-page" %>
      <% if order.sending_user.present? %>
        　<%= link_to order.sending_user.company_name, order_path(order), class: "show-page" %>
      <% end %>
    </div>
  <% end %>
</div>


<div class="contents-row">
  <p>受注一覧</p>
  <% @matched_orders.reverse_each do |order| %>
    <% if order.sending_user_id == current_user.id %>
      <div class="order-index">
        ◇ <%= link_to order.delivery_day, order_path(order), class: "show-page" %>
        <%= link_to order.user.company_name, order_path(order), class: "show-page" %>
      </div>
    <% end %>
  <% end %>
</div>